spring.application.name=demo

# Server port
server.port=8080

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/clothes_5
spring.datasource.username=root
spring.datasource.password=chung0803@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# JWT Configuration
# application.properties
#jwt.secret=6d5775091ee7118aa63cf885fbde1924c05fa6ae19f8434c1f2efac1978fd4c211727daea62eff3c3afed314d625f6c466531efe6b833fd0100e9689a0e221f0ac213e42c229f4bb3caf5c05e2bd28b5e500c8b64addd2932c2e59d64cc3dc9e1815c036c5446784bfe27c066bcf58f5ec0b9c31ce212eace1a69593779730a365ee7ff844a2789073744c130ac3e86c1d7ccb713b82b9047dedb53bf29e4de4d52084780f3e8a2aeae51f18daba8f87a2079939331eb6f8e48c1610cb3f7c5bf3870fe69665b0a06888359b3604bb5e449297cc9686d51944398db9cd80eeb178e0e3f196368eecb298c48cf97e7cb28bbf9c9d7b9da0ed424b523dd2e3ec92
#jwt.expiration=86400000

# Log JWT secret
#logging.level.com.example.demo.config=DEBUG

# Log when JWT token is validated and any errors
#logging.level.com.example.demo.security.JwtAuthenticationFilter=DEBUG
#
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=trace
#
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.security.web=DEBUG
#logging.level.org.springframework.security.authentication=DEBUG


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chungvan704@gmail.com
spring.mail.password=bsao pvpe rbrk jdvt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

