spring.application.name=demo
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/clothes_5
spring.datasource.username=root
spring.datasource.password=chung0803@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.web.resources.add-mappings=false
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=trace
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web=DEBUG
logging.level.org.springframework.security.authentication=DEBUG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chungvan704@gmail.com
spring.mail.password=bsao pvpe rbrk jdvt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

